services:
  ea-see-face-recognition:
    build:
      dockerfile: docker/ea-see.Dockerfile
      context: .
    command: uvicorn ea_see.serve:app --host 0.0.0.0 --port ${SERVER_PORT}
    environment:
      CONDA_ENV: ${CONDA_ENV}
      PYTHON_VERSION: ${PYTHON_VERSION}
      DATASET_FILE: ${DATASET_FILE}
      DATASET_DOWNLOAD_URL: ${DATASET_DOWNLOAD_URL}
      WEIGHTS_FILE: ${WEIGHTS_FILE}
      WEIGHTS_DOWNLOAD_URL: ${WEIGHTS_DOWNLOAD_URL}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./${WEIGHTS_FILE}:/app/models/${WEIGHTS_FILE}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              